name: Shell Command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-windows-command:
    runs-on: windows-latest
    # "run-shell-command"の実行を待ってからの実行となる
    needs: ["run-shell-command"]
    steps:
      - name: Directory
        run: Get-location
      - name: Directory Bash
        run: pwd
        shell: bash          
